### PR TITLE
header component

### PR DESCRIPTION
**Pull request by Shadi38**
created header component

### CODE REVIEW

**Review by Junitalama — COMMENTED** [review]
Looks good

**Review by Afsha10 — COMMENTED** [review]
Hi @Shadi38 !
I have tried to run the app with your branch with npm start. This is what I got and something is wrong. Could you try if it works on your computer?

Screenshot from 2023-11-20 11-38-32

**Comment by Shadi38** [comment]
hi Afsha
this code in this branch works in my computer.
the error you are facing with is related content.js  line 3 that is not in this branch.
Screenshot 2023-11-20 at 20 25 09

**Review by Afsha10 — APPROVED** [review]
Well done @Shadi38 ! 
To address the conflicts below we need to create a branch from the main and then we need to add the codes you have written and all the changes you have made on top of that main branch and tackle each of those conflicts. :)

**Review by Junitalama — APPROVED** [review]

**Pull request merged**
