### PR TITLE
Playlist input

### PR DESCRIPTION
**Pull request by Shadi38**
In the MainScreen component, code was added to retrieve the access token from the getToken function and utilize it in the handleSubmit function for making a GET API request to access the playlist from Spotify.

### CODE REVIEW

**Review by Afsha10 — COMMENTED** [review]
If we are using the PKCE method we don't need the backend. We can log in on the front-end and fetch the playlist on the front-end. 
I think you are using Client Credentials method. With this method we will not be able to upload a modified playlist because it cannot access users account. 
We should agree on which method to use.

**Comment by Shadi38** [comment]
the code in back end  was  related to last week for accessing the fresh Token and I forgot to delete that.
I will delete that code in back end  and will push new changes to this branch

**Review by Afsha10 — COMMENTED** [review]
Hi @Shadi38 !
We need to make small components (like SharedPlaylistInputBox) in our branch instead of adding to the MainScreen and making it huge. I'm sure you can make these changes. :)

**Comment by Shadi38** [comment]
I changge the code and made it smaller

**Pull request merged**
